import React from "react";

function BackgroundGalleryListItem() {
    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            overflow="hidden"
            style={{
                width: "100%",
                height: "100%",
                WebkitTransformOrigin: "0",
                MsTransformOrigin: "0",
                transformOrigin: "0"
            }}
        >
            <g style={{ transform: `rotate(45deg) scale(1.5)`}}>
                <rect
                    width="0%"
                    height="5.882%"
                    x="75%"
                    y="11.765%"
                    fill="none"
                    stroke="#00C6FF"
                />
                <rect
                    width="37.5%"
                    height="5.882%"
                    x="75%"
                    y="52.941%"
                    fill="#0072FF"
                    stroke="#0072FF"
                />
                <rect
                    width="25%"
                    height="5.882%"
                    x="50%"
                    y="58.824%"
                    fill="none"
                    stroke="#00C6FF"
                />
                <rect
                    width="12.5%"
                    height="5.882%"
                    x="62.5%"
                    y="82.353%"
                    fill="#0072FF"
                    stroke="#0072FF"
                />
                <rect
                    width="12.5%"
                    height="5.882%"
                    x="0%"
                    y="52.941%"
                    fill="none"
                    stroke="#00C6FF"
                />
                <rect
                    width="12.5%"
                    height="5.882%"
                    x="25%"
                    y="41.176%"
                    fill="#0072FF"
                    stroke="#0072FF"
                />
                <rect
                    width="25%"
                    height="5.882%"
                    x="25%"
                    y="0%"
                    fill="#00C6FF"
                    stroke="#00C6FF"
                />
                <rect
                    width="12.5%"
                    height="5.882%"
                    x="50%"
                    y="47.059%"
                    fill="#0072FF"
                    stroke="#0072FF"
                />
                <rect
                    width="37.5%"
                    height="5.882%"
                    x="37.5%"
                    y="82.353%"
                    fill="#00C6FF"
                    stroke="#00C6FF"
                />
                <rect
                    width="25%"
                    height="5.882%"
                    x="87.5%"
                    y="82.353%"
                    fill="#0072FF"
                    stroke="#0072FF"
                />
                <rect
                    width="12.5%"
                    height="5.882%"
                    x="75%"
                    y="17.647%"
                    fill="none"
                    stroke="#00C6FF"
                />
                <rect
                    width="37.5%"
                    height="5.882%"
                    x="0%"
                    y="47.059%"
                    fill="#0072FF"
                    stroke="#0072FF"
                />
                <rect
                    width="25%"
                    height="5.882%"
                    x="0%"
                    y="0%"
                    fill="#00C6FF"
                    stroke="#00C6FF"
                />
                <rect
                    width="37.5%"
                    height="5.882%"
                    x="50%"
                    y="58.824%"
                    fill="none"
                    stroke="#0072FF"
                />
                <rect
                    width="25%"
                    height="5.882%"
                    x="75%"
                    y="52.941%"
                    fill="#00C6FF"
                    stroke="#00C6FF"
                />
                <rect
                    width="12.5%"
                    height="5.882%"
                    x="50%"
                    y="52.941%"
                    fill="#0072FF"
                    stroke="#0072FF"
                />
            </g>
        </svg>
    );
}

export default BackgroundGalleryListItem;
